<!--
%\VignetteEngine{knitr::knitr}
%\VignetteIndexEntry{Basic}
\usepackage[utf8]{inputenc}
-->

An example vignette
-----


```{r echo=FALSE,message=FALSE,results='hide',warning=FALSE}
library(openScienceExample)
```

This is a basic vignette, designed to show how one and include data and analysis in an R package.


### Loading the data set
```{r}
data('ci.data')
```


### Clean the data set
```{r}
dataNoStudents = openScienceExample::cleanData()
```

### Making a plot

```{r fig.width=6,fig.height=5.5}

## Create a bivariate frequency table 
expTable = with( dataNoStudents,
                table( floor( expertise ), 
                       floor( Nendorsed )
                       ) 
                )

## graphical parameters
par( las=1, cex.lab=1.2, cex.axis=1.2 )

## Create image plot
image(x = as.numeric( rownames( expTable ) ), 
      y = as.numeric( colnames( expTable ) ),
      z = expTable,
      col  = gray( ( 15:0 ) / 15 ),
      ylab="Number of endorsements",
      xlab="Self-rated experience")

## Add numbers     
for(i in 1:nrow( expTable ) )
  for(j in 1:ncol( expTable ) ){
    n = expTable[ i, j ]
    if( n > 0 ) text( i, j - 1, n )
    if( n > 9 ) text( i, j - 1, n, col = "white" )
  }

## Add a box
box()

```

